spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/zemarket}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:Amos1436}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        type:
          preferred_uuid_jdbc_type: BINARY
    show-sql: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${JWT_SECRET:your-jwt-secret-key-here}

  mail:
    host: ${SPRING_MAIL_HOST:localhost}
    port: ${SPRING_MAIL_PORT:1025}
    username: ${SPRING_MAIL_USERNAME:}
    password: ${SPRING_MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: ${SPRING_MAIL_SMTP_AUTH:false}
          starttls:
            enable: ${SPRING_MAIL_SMTP_STARTTLS:false}

app:
  jwt:
    expiration: 86400000
    secret: ${JWT_SECRET:change-me-to-a-very-long-256-bit-secret-change-me-change-me}

  qrcode:
    size: 300
    format: PNG

  file:
    upload-dir: ./uploads

  email:
    from: no-reply@plateforme.local

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    com.plateforme: DEBUG
    org.springframework.security: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
